### ISSUE TITLE
Feedback for milestone 3

### ISSUE THREAD

**Issue by lmguzman** [UBC-MDS/image-compression-toolkit--R#23]
Good job with your package! you chose a hard topic and have done an exceptional work on getting your package to work. 

Here is some feedback I have after installing and running your functions. Please incorporate it for your next submission. 

- You need examples in your documentation
- While OpenImageR has identified as a dependency, it is not imported into your function. You need to update your roxygen comments so it says @import OpenImageR
    - crop("milestone2/Image_compression/image_2.png", 2, 3,    "milestone2/Image_compression/image_2_milestone3.png")
    - Error in readImage(img_path) : could not find function "readImage"

- I'm not sure what is the error in this case, but I tried to use your compress function and I get the following error:
   - compress("milestone2/Image_compression/image_2.png", 2,"milestone2/Image_compression/image_2_milestone3.png")
   - Error in compress("milestone2/Image_compression/image_2.png", 2, "milestone2/Image_compression/image_2_milestone3.png") : 
    - TypeError

- Ok, finally I figured out that to pass your is.integer condition, I needed to input 2L, not just 2. I would suggest you clarify this in your documentation. But I still get the same error as above, probably because you don’t import the other packages to your function. 

- I think in general it would be useful if your stop messages were more meaningful, since I had to go into your function and test all my inputs to see which one was creating the error. At the very least it should say TypeError of blah blah input. 

- You need to build your vignette. 

- All your tests passed in your python and R packages (yay!), but when I was checking your R package I got the following warnings:

❯ checking whether package ‘imageCompressR’ can be installed ... WARNING
  See below...

❯ checking package subdirectories ... WARNING
  Subdirectory ‘data’ contains no data sets.

❯ checking contents of ‘data’ directory ... WARNING
  Files not of a type allowed in a ‘data’ directory:
    ‘bigger_test.png’ ‘branch_coverage.png’ ‘compressed_img.png’
    ‘crop_img.png’ ‘test_results.png’
  Please use e.g. ‘inst/extdata’ for non-R data files

❯ checking DESCRIPTION meta-information ... NOTE
  Malformed Description field: should contain one or more complete sentences.

❯ checking R code for possible problems ... NOTE
  compress: no visible global function definition for ‘readImage’
  compression: no visible global function definition for ‘readImage’
  compression: no visible global function definition for ‘kmeans’
  compression: no visible global function definition for ‘writePNG’
  crop: no visible global function definition for ‘readImage’
  crop: no visible global function definition for ‘rem’
  crop: no visible global function definition for ‘writePNG’
  Undefined global functions or variables:
    kmeans readImage rem writePNG
  Consider adding
    importFrom("stats", "kmeans")
  to your NAMESPACE file.

❯ checking Rd files ... NOTE
  prepare_Rd: compress.Rd:23-25: Dropping empty section \examples
  prepare_Rd: crop.Rd:24-27: Dropping empty section \examples
  prepare_Rd: image_size.Rd:18-20: Dropping empty section \examples

0 errors ✔ | 3 warnings ✖ | 3 notes ✖
Error: R CMD check found WARNINGs
Execution halted

Exited with status 1.

**Comment by Sayanti86** [comment]
Hi @lmguzman , 

All of the below feedback have been taken care of : 

- [x] You need examples in your documentation

- [x] While OpenImageR has identified as a dependency, it is not imported into your function. You need to update your roxygen comments so it says @import OpenImageR

- [x] crop("milestone2/Image_compression/image_2.png", 2, 3, "milestone2/Image_compression/image_2_milestone3.png")
Error in readImage(img_path) : could not find function "readImage"
I'm not sure what is the error in this case, but I tried to use your compress function and I get the following error:

- [x] compress("milestone2/Image_compression/image_2.png", 2,"milestone2/Image_compression/image_2_milestone3.png")
Error in compress("milestone2/Image_compression/image_2.png", 2, "milestone2/Image_compression/image_2_milestone3.png") :
TypeError

- [x] Ok, finally I figured out that to pass your is.integer condition, I needed to input 2L, not just 2. I would suggest you clarify this in your documentation. But I still get the same error as above, probably because you don’t import the other packages to your function.

- [x] I think in general it would be useful if your stop messages were more meaningful, since I had to go into your function and test all my inputs to see which one was creating the error. At the very least it should say TypeError of blah blah input.

- [x] You need to build your vignette.

- [x] All your tests passed in your python and R packages (yay!), but when I was checking your R package I got the following warnings:
